### ISSUE TITLE
Inbreeding values using NgsAdmix

### ISSUE THREAD

**Issue by ericgonzalezs** [arundurvasula/angsd-wrapper#102]
Hi Arun,

I want to run NgsAdmix and using inbreeding coefficients. I don´t understand how your scripts take in to account ibreeding coefficients. Could you plese tell me in which step you are including the inbreeding coefficients? 

Best Wishes,

Eric

**Comment by arundurvasula** [comment]
Hi Eric,

This repository has a more recent version of ANGSD-wrapper: https://github.com/mojaveazure/angsd-wrapper

Our implementation does not currently use inbreeding coefficients for NgsAdmix.

Best,
Arun
