### ISSUE TITLE
Option to plot SFS

### ISSUE THREAD

**Issue by tvkent** [arundurvasula/angsd-wrapper#19]
Add option to plot SFS using the ANGSD file.saf.sfs.  May be useful to have in the same place as the thetas.  ANGSD has their plot code here: http://popgen.dk/angsd/index.php/SFS_Estimation

**Comment by arundurvasula** [comment]
Many months later...added! Commit https://github.com/arundurvasula/angsd-wrapper/commit/0f7a048f8e883c412d6e9dda7dbec8c9ac2f9e25
