### ISSUE TITLE
should common.conf be sourced in the scripts?

### ISSUE THREAD

**Issue by arundurvasula** [arundurvasula/angsd-wrapper#48]
Latest commit: https://github.com/arundurvasula/angsd-wrapper/commit/445b861e52f7e83590c5c22b33114d93d70e4362 moved a lot of variable declarations to a common.conf file, but that file needs to be sourced in the script files in order to be used right? Running ANGSD_SFS with the default conf gives the following error:

    scripts/ANGSD_SFS.sh: line 95: ANGSD_DIR: unbound variable

I think because it can't find that declaration. Adding `source common.conf` before loading the user supplied configuration ([here](https://github.com/arundurvasula/angsd-wrapper/blob/master/scripts/ANGSD_SFS.sh#L24)) should fix this.

**Comment by dmvelasco** [comment]
In this vein. Does `${HOME}` in `PROJECT_DIR=${HOME}/angsd-wrapper` of common.conf file need to be defined somewhere or is it pulled from elsewhere? (I have not used angsd-wrapper but am just trying to understand a bit about how it works first.)

Thanks

**Comment by arundurvasula** [comment]
Nope it should be okay. $HOME is an environment variable that should
automatically be set to your home directory.

**Comment by pmorrell** [comment]
Sorry, $HOME might have been my addition, with minimal explanation.
