### ISSUE TITLE
stuff we want

### ISSUE THREAD

**Issue by rossibarra** [arundurvasula/angsd-wrapper#58]
Fst
Make ancestral genome
Call genotypes
Thetas
plotting thetas
SFS
plot sfs
fst
plotting fst
estimate inbreeding
admixture
plot admixture
PCA
plot pca
ABBA-BABBA
plot ABBA-BABBA ?

**Comment by arundurvasula** [comment]
Progress as of now:

[x]Fst
[ ]plotting fst
[ ]Make ancestral genome (Tyler)
[ ]Call genotypes
[x]Thetas
[x]plotting thetas
[x]SFS
[ ]plot sfs
[ ]estimate inbreeding (Tyler)
[x]admixture
[ ]plot admixture
[ ]PCA
[ ]plot pca
[x]ABBA-BABA
[x]plot ABBA-BABA

7/15 done!

**Comment by rossibarra** [comment]
Me want to see abba graphs.

**Comment by arundurvasula** [comment]
Crap didn't mean to mark plot ABBA-BABA as done, but I'll get it done next since I marked it.

**Comment by arundurvasula** [comment]
[x]Fst
[ ]plotting fst
[ ]Make ancestral genome (Arun)
[ ]Call genotypes
[x]Thetas
[x]plotting thetas
[x]SFS
[x]plot sfs
[x]estimate inbreeding (Tyler)
[x]admixture
[x]plot admixture
[ ]PCA
[ ]plot pca
[x]ABBA-BABA
[x]plot ABBA-BABA

**Comment by arundurvasula** [comment]
[x]Fst
[ ]plotting fst (Tyler)
[x]Make ancestral genome
[ ]Call genotypes (Sid/Tyler)
[x]Thetas
[x]plotting thetas
[x]SFS
[x]plot sfs
[x]estimate inbreeding
[x]admixture
[x]plot admixture
[x]PCA
[ ]plot pca (Arun)
[x]ABBA-BABA
[x]plot ABBA-BABA

**Comment by arundurvasula** [comment]
Genotypes added in last commit.
