### ISSUE TITLE
add reference fasta sort fix

### ISSUE THREAD

**Issue by arundurvasula** [arundurvasula/angsd-wrapper#67]
for i in `seq 1 12`; do samtools faidx ref.fa $i >> sorted_ref.fa; done

Then gzip your fasta and run

    samtools faidx sorted_ref.fa.gz

to get your .fai file.

**Comment by tvkent** [comment]
this was bc ref fastas weren't working if the chromosomes were out of order

**Comment by arundurvasula** [comment]
Added to FAQ
