### ISSUE TITLE
check all scripts for file_exists

### ISSUE THREAD

**Issue by tvkent** [arundurvasula/angsd-wrapper#70]
this doesn't actually check if the files exist bc it's not a command. Use if [ -e "$file" ]; then 
instead

**Comment by tvkent** [comment]
also use if [ ! -e "$file"] if you're checking if a file doesn't exist #echolobo

**Comment by arundurvasula** [comment]
https://github.com/arundurvasula/angsd-wrapper/blob/master/scripts/utils.sh
