### ISSUE TITLE
echo stuff

### ISSUE THREAD

**Issue by tvkent** [arundurvasula/angsd-wrapper#72]
change echo output to std err since angsd sends stuff there. makes output easier to follow.
i.e.: >&2 echo "stuff"

**Comment by tvkent** [comment]
maybe have a flag before angsd-wrapper echoes so we know what it is i.e.: ANGSD-WRAPPER: some message.
this may just be a preference thing for me, but i think it makes it easier to debug

**Comment by arundurvasula** [comment]
👍 Yeah that makes sense.

**Comment by tvkent** [comment]
i fixed these i think
