### ISSUE TITLE
option to add filename extensions

### ISSUE THREAD

**Issue by tvkent** [arundurvasula/angsd-wrapper#78]
add option to put extensions on input and output files so analyses can be run with multiple options without overwriting or stopping bc the file already exists.
this should also mean that piggybacked analyses (thetas, fst) call in the conf file of the first step (sfs, 2dsfs) and run a check to make sure the output file extension of the first matches the input file extension of the second to protect against accidentally using the wrong input files.
also include a warning somewhere about changing file names being dangerous and it's not our fault if you don't double check your inputs

**Comment by arundurvasula** [comment]
No.

**Comment by tvkent** [comment]
lmao ok
