### ISSUE TITLE
Configuration confusing and limiting

### ISSUE THREAD

**Issue by mojaveazure** [arundurvasula/angsd-wrapper#85]
Using angsd-wrapper is far to confusing to make it useful. I've had to edit three different configuration files to try and use ANGSD via angsd-wrapper while following the tutorial listed on this GitHub repository, but it's getting frustrating.

I would recommend condensing all options to one configuration file, and also not having defaults for directories and names. Please make this easily user-configurable.

**Comment by arundurvasula** [comment]
Hi,

Thanks! One of the things we're working on right now is streamlining this process and updating the tutorial/documentation. As soon as we finish up the features we will work on this. 

I think we will be moving to one configuration file soon.

**Comment by mojaveazure** [comment]
Awesome, thank you!

**Comment by mojaveazure** [comment]
Hi Arun,

I've forked your version of angsd-wrapper and started reworking the configuration files and wrapper scripts to make it, in my opinion, easier to use. I've done this so far with the SFS and 2D SFS scripts. I have also updated the wrappers a little to work with the most recent version of ANGSD. You can see what I've done [here](https://github.com/mojaveazure/angsd-wrapper); if you'd like, I'd be more than happy to help do this with the rest of ansd-wrapper.

**Comment by rossibarra** [comment]
Updating to work with most recent version of ANGSD would be good. Arun you
should make a release based on your current wrapper; that's what will go
with the paper.  But no reason not to update to newest version and if we
can get it done ASAP no reason not to include Paul on the paper?

-J

____________

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by tvkent** [comment]
collaboration ongoing
