### ISSUE TITLE
Header Requirements

### ISSUE THREAD

**Issue by mojaveazure** [arundurvasula/angsd-wrapper#86]
The current version of SAMtools is no longer creating headers.
Using their dataset, I have run:
> `samtools view -bS toy.sam | sort - toy`
> `samtools view -bT toy.fa toy.sam | sort - toy`

to create sorted bam files. Each time, I get the following bam file
`samtools view -H toy.bam | head`
> `@SQ    SN:ref      LN:45`
> `@SQ    SN:ref2    LN:40`

Can the requirement for headers starting with @HD be removed? Surely there's a way to find specific regions without @HD headers.

**Comment by arundurvasula** [comment]
I don't think we can do this with angsd-wrapper but it may be possible to add it to ANGSD? Try: https://github.com/angsd/angsd
