### ISSUE TITLE
common variables

### ISSUE THREAD

**Issue by tvkent** [arundurvasula/angsd-wrapper#92]
i'm noticing some common variables in example conf files. I don't want to remove them bc idk if the common file is being properly sourced in all the .sh scripts, but if they are being sourced in the common file, they should be removed from the conf files to avoid confusion

**Comment by arundurvasula** [comment]
Which files still have these?

**Comment by tvkent** [comment]
bro idk check them

On Wed, Sep 16, 2015 at 6:17 PM, Arun Durvasula <notifications@github.com>
wrote:

> Which files still have these?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arundurvasula/angsd-wrapper/issues/92#issuecomment-140910406>
> .
>



-- 
Tyler Kent

Wright Lab
Department of Ecology and Evolutionary Biology
University of Toronto
25 Willcocks St.
Room 3025
Toronto, ON
Canada M5S 3B2
