### ISSUE TITLE
shiny thetas and SFS graphing issues

### ISSUE THREAD

**Issue by liux1299** [arundurvasula/angsd-wrapper#96]
### Thetas graph
Shiny plots each point for each contig on separate graphs instead of all on the same graph. This has been the same result for both the test dataset used in the tutorial and on a real dataset I've been using to test angsd-wrapper. 

I get this:

![thetas test dataset graph issue](https://cloud.githubusercontent.com/assets/7061412/10077710/21b82ff6-62a7-11e5-97cf-6555c21d9a38.png)

Instead of this for the theta graph:

![thetas test dataset graph - correct](https://cloud.githubusercontent.com/assets/7061412/10077728/2f45131e-62a7-11e5-9ec8-0577032be812.png)

### SFS graph
There have also been issues with shiny graphing SFS. Below is the output for the test dataset:
![sfs test dataset graph issue](https://cloud.githubusercontent.com/assets/7061412/10077765/52293266-62a7-11e5-97d7-140e95739560.png)

Which should look like this according to the tutorial:

![sfs test dataset graph - correct](https://cloud.githubusercontent.com/assets/7061412/10077776/60bef176-62a7-11e5-8786-f150e4880654.png)

I'm attempting to debug shiny.

**Comment by arundurvasula** [comment]
Hi,

Thanks for submitting an issue! Regarding the site frequency spectrum, you
are going to want to graph the file called "test_DerivedSFS" instead of the
.arg file.

I'm not sure what's going on with the thetas issue. Can you upload your
results file somewhere (eg Dropbox or Google Drive) and send it to me so I
can try it out?

Thanks!

**Comment by liux1299** [comment]
Hi,

I had tried using the "test_DerivedSFS" file initially and got a graph that looked like this:

 
![test_derivedsfs graph issue](https://cloud.githubusercontent.com/assets/7061412/10106621/6026c3ae-637b-11e5-903e-bd6d47d8028c.png)

And yes, I will send my results file to you via Dropbox.

Thanks!

**Comment by arundurvasula** [comment]
Regarding the SFS issue, the output of realSFS changed between the version ANGSD-wrapper uses and the current version (0.9). If you would like to use the output from the new version, please add `-oldout 1` to the command line where realSFS is called and the output will be compatible with the shiny graphing.

I'm going to close this issue and reopen one for the thetas.
