### ISSUE TITLE
Errors when working through tutorial

### ISSUE THREAD

**Issue by liux1299** [arundurvasula/angsd-wrapper#99]
## Comments on Tutorial
- When calling on samtools, it would be helpful to mention to users they need to load samtools or install samtools if they do not already have samtools installed.

## Error messages
Here are some errors that I came across when working through ANGSD-wrapper's tutorial:
- When running the following command:
```
$ samtools faidx data/reference.Oryza_sativa.IRGSP-1.0.23.dna.genome_chr.fa.gz
```
The following error message is outputted:
```
Cannot index files compressed with gzip, please use bgzip
```
`bgzip` is not a command, should mention to users how to unzip the file otherwise they are not able to run through the remainder of the tutorial
	- Solution: use gunzip to decompress fasta files

- Running the following command:
```
bash scripts/SFS.sh scripts/SFS.conf
```
Error message:
```
scripts/SFS.sh: line 127: /home/morrellp/liux1299/ANGSD-wrapper_beta_testing/aw_test_iplant1_AD/aw-tutorial/angsd/misc/realSFS: No such file or directory
```

I will continue testing the remainder of the scripts and see if they are able to run to completion.

**Comment by rossibarra** [comment]
bgzip is part of HTSLIB and runs just fine on my cluster. Arun are your
files bgzip'd? Perhaps we just need to mention people need to have
htslib/samtools installed?

 $ bgzip

Usage:   bgzip [options] [file] ...

Options: -c      write on standard output, keep original files unchanged
         -d      decompress
         -f      overwrite files without asking
         -b INT  decompress at virtual file pointer INT
         -s INT  decompress INT bytes in the uncompressed file
         -h      give this help



____________

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by rossibarra** [comment]
Is /home/morrellp/liux1299/ANGSD-wrapper_beta_testing/aw_test_
iplant1_AD/aw-tutorial/angsd/misc/ a real directory? All line 127 is doing
is:

${ANGSD_DIR}/misc/realSFS\ ${RESULTS_DIR}/

It looks like there might be a forward slash missing before ${RESULTS_DIR},
but without knowing what you put in the config file I'm not totally sure.

____________

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by tvkent** [comment]
can you not just do something like zless data/reference.Oryza_sativa.IRGSP-1.0.23.dna.genome_chr.fa.gz | samtools faidx -
?
I always gzip and constantly gzipping and gunzipping is a bad idea.

**Comment by liux1299** [comment]
Yes, `/home/morrellp/liux1299/ANGSD-wrapper_beta_testing/aw_test_
iplant1_AD/aw-tutorial/angsd/misc/` is a real directory. I checked in the directory but did not find `realSFS` in it. I think the issue might be an error with installating angsd.

When running `make` in `angsd` directory, I get the following error:
```
g++ -O3 -D_USE_KNETFILE  -o angsd.static *.o -lz -lpthread --static                                             
/usr/bin/ld: cannot find -lz                                                                                    
collect2: ld returned 1 exit status                                                                             
make: *** [angsd.static] Error 1                                                                                
```

**Comment by rossibarra** [comment]
That's the lib error you guys have on your system. Make a note in the
wiki/tutorial that you need zlib installed, and that should be the end of
that issue.

____________

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by rossibarra** [comment]
Yes, this is a better solution.

____________

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by pmorrell** [comment]
Just ask yourself, "What would Vince Buffalo do?". He would use a pipe.

Sent from my iPhone

On Nov 3, 2015, at 15:53, Jeffrey Ross-Ibarra <notifications@github.com>
wrote:

Yes, this is a better solution.

____________

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org


On Tue, Nov 3, 2015 at 12:44 PM, Tyler Kent <notifications@github.com>
wrote:

> can you not just do something like zless
> data/reference.Oryza_sativa.IRGSP-1.0.23.dna.genome_chr.fa.gz | samtools
> faidx -
> ?
> I always gzip and constantly gzipping and gunzipping is a bad idea.
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/arundurvasula/angsd-wrapper/issues/99#issuecomment-153482372
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/arundurvasula/angsd-wrapper/issues/99#issuecomment-153500993>
.

**Comment by arundurvasula** [comment]
Put the zlib thing in the installation instructions, FAQ, and tutorial. Will close issue.
